name: Build and Publish Images

on:
  push:
    tags: [ 'ruby-*.*.*' ]

jobs:
  build:
    name: Build Images

    strategy:
      fail-fast: false
      matrix:
        RUBY_VERSION:
          - 3.3.1
          - 3.0.7

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Build and Publish Image
        uses: ./.github/actions/build-and-publish-image
        with:
          ruby_version: ${{ matrix.RUBY_VERSION }}
          image_tag:  ${{ github.ref_name }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
